### ISSUE TITLE
Missing db import

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-flask-sqlalchemy#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/208459?module_item_id=480473

### Concern

In our first code example under our **Flask Migrate** section, we've neglected to import `db` from `models`. This causes an error when students try to run `flask db init`.

The correct version is included in our solution code.

**Comment by professor-ben** [comment]
Thanks for the tip- just updated!
